innova/urls.py
from django.urls import path
from . import views

app_name = 'innova'


urlpatterns = [

    path('',views.home,name='Home'),
    path('company',views.company,name='company'),
    path('our-board',views.ourBoard,name='our-board'),
    path('reporting',views.reporting,name='reporting'),
    path('plasma-protein',views.plasmaProtein,name='plasma-protein'),
    path('food-supplements',views.foodSupplements,name='food-supplements'),
    path('careers',views.careers,name='careers'),
    path('contact',views.contact,name='contact'),
    path('applyFilter/<int:category>',views.applyFilter,name='applyFilter'),

    path('ProductDetails/<str:productcategory>/<str:product>',views.productDetails,name='productDetails'),
    path('ProductDetails/<str:product>',views.patientsArea,name='patientsArea'),

    path('productDetailsFood/<str:productcategory>/<str:product>',views.productDetailsFood,name='productDetailsFood'),
    path('productDetailsFood/<str:product>',views.patientsAreaFood,name='patientsAreaFood'),

    path('News/<int:id>',views.newsDetails,name='newsDetails'),
    path('Ourboard/<int:hash>',views.ourBoardHash,name='ourboardhash'),
    path('Company/<int:hash>',views.companyhash,name='companyhash'),

]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('innova/',include('innova.urls',namespace='innova')),
    path('',include('account.urls',namespace='account')),
    path("__debug__/", include("debug_toolbar.urls"))
]

urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/webPage/Home.html
{% extends 'mainTemplates/mainPage.html' %}
{% load static %}
{% load humanize %}

{% block section1 %}
    <!-- slider -->
    <section class="slider home3">
        <div class="elip-header4 animate-rotate">
            <img src="{% static 'assets/images/mark-page/Innova.png' %}" class="img-max_width" alt="img">
        </div>
        <!-- <div class="elip-header5 animate-up">
            <img src="{% static 'assets/images/mark-page/health.png' %}" alt="img">
        </div> -->
        <div class="container-fuild">
            <div class="swiper-container mainslider">                            
                <div class="swiper-wrapper">
                    {% for slide in slideData %}
                        <div class="swiper-slide">
                            <div class="flat-slider">  <div class="overlay-slider style"></div>
                            <div class="sld-img"><img src="{{slide.image.url}}" alt=""></div>
                                <div class="content col-md-6 col-sm-12">
                                    <div class="heading">
                                        <h1>{{slide.subject}}</h1>
                                        <p>{{slide.content }}
                                        </p>
                                    </div>
                                    <!-- <div class="button-slider">
                                        <a href="#" class="button btn-style3 btn-1"><span>Discover More </span></a>
                                    </div> -->
                                </div>
                            </div>                           
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>               
        <div class="button-custom-slider">
            <div class="swiper-button-next button-slide-custom-next"></div>
            <div class="swiper-button-prev button-slide-custom-prev"></div>
        </div>
    </section>
{% endblock %}



{% block section2 %}
<!-- flat trusted -->
<section class="tf-space flat-trusted">
    <div class="container">
        <div class="row">
            {% for partner in partnerData %}
            <div class="col-lg-6 col-md-5 wow fadeInLeft" data-wow-delay="100ms" data-wow-duration="800ms">
                <div class="media-box">
                    <div class="mediafull">
                        <img src="{{partner.Image.url}}" alt="images">                                                                   
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-7 wow fadeInRight" data-wow-delay="0ms" data-wow-duration="800ms">
                <div class="trusted-heading-without-marge wow fadeInUp" data-wow-delay="0ms" data-wow-duration="1100ms">
                    <h2 class="tf-title">Our <span class="text-color-3 style-title">Partner</span></h2>
                </div>
                    <!-- <h3 class="text-color-3">At Innova,</h3> -->
                    <p>{{partner.description|linebreaks}}</p> 
                    <div class="img-title50 wow fadeInDown" data-wow-delay="100ms" data-wow-duration="1100ms" style="padding-top: 10px;">
                        <a href="{{partner.website}}">
                            <img src="{{partner.logo.url}}" alt="images">   
                        </a>
                    </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

{% block section3 %}
<!-- flat brand -->
<section class="flat-brand">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="team-heading wow fadeInDown" data-wow-delay="0ms" data-wow-duration="700ms">
                    <h2 class="tf-title text-color-1">Products</h2>
                </div>
            </div>
            <div class="col-lg-12 col-md-12">
                <div class="brand-slider">
                    <div class="swiper-container carousel-4">
                        <div class="swiper-wrapper">
                            
                            {% for product in products %}
                                <div class="swiper-slide wow zoomInLeft" style="width: 180px;height: 270px;" data-wow-delay="0ms" data-wow-duration="1100ms">
                                    <div class="slogan-logo" style="height: 100%;">
                                        <a href="{% url 'innova:patientsArea' product=product.name %}">
                                            <img src="{{product.Image.url}}" alt="images" style="height: 85%;">
                                        </a>
                                        <div class="content-white"> 
                                            <h3 >{{product.name}}</h3>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block section4 %}
<section class="tf-space flat-blog-grid home03">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="blog-heading wow fadeInDown" data-wow-delay="0ms" data-wow-duration="500ms">
                    <h2 class="tf-title">Company <span class="text-color-3 style-title">Blog</span></h2>
                </div>
            </div>
            {% for news in newsData %}
            <div class="col-lg-4 col-md-4">
                <div class="grid-post">
                    <div class="media height-150 wow fadeInUp" data-wow-delay="0ms" data-wow-duration="1500ms">
                        <img src="{{news.image.url}}" alt="images">
                    </div>
                    <div class="content">
                        <h3 class="title-item"><a href="blog-details.html">{{news.subject}}</a></h3>
                        <p>{{news.content}}</p>
                    </div>
                </div>
            </div>  
            {% endfor %}                   
        </div>
    </div>
</section>

<!-- flat service -->
<!-- <section class="tf-space flat-service home2 home3">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="service-heading wow fadeInDown" data-wow-delay="0ms" data-wow-duration="1500ms">
                    <h2 class="tf-title">Company <span class="text-color-3 style-title">Blog</span></h2>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="swiper-container service-slider carousel-4">
                    <div class="swiper-wrapper">
                        {% for news in newsData %}
                            <div class="swiper-slide service-post post wow fadeInUp" data-wow-delay="0ms" data-wow-duration="1500ms">
                                <div class="media">
                                    <img src="{{news.image.url}}" alt="images">                                
                                </div>
                                <div class="content">                                  
                                    <h3>{{news.subject}}</h3> 
                                    <div class="tf-progress"></div> 
                                    <p class="p-hover">{{news.content|slice:":50" }}...</p> 
                                    <ul>
                                        <li><a href="{% url 'innova:newsDetails' id=news.id %}">Read More</a></li> 
                                    </ul>                                 
                                </div>
                            </div>
                        {% endfor %}
                    </div>                                                               
                </div>
            </div>     
        </div>
    </div>
</section> -->
{% endblock %}

{% block section5 %}
<!-- flat servece -->
<section class="tf-space flat-servece">
    <div class="overlay-page"></div>
</section>

<!-- flat team -->
<section class="flat-team flat-blog-grid home3">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="team-heading wow fadeInDown" data-wow-delay="0ms" data-wow-duration="500ms">
                    <h2 class="tf-title text-color-1">Management Team</h2>
                </div>
            </div> 
            <div class="col-lg-1">
            </div>     
                     
            {% for board in boardMember %}
            <div class="col-lg-2 col-md-6">
                <div class="team-box grid-post wow fadeInUp" data-wow-delay="0ms" data-wow-duration="1500ms">
                    <div class="media">
                        <img src="{{board.Image.url}}" alt="images">                                
                    </div>
                    <div class="content"> 
                        <div class="sub-title-content">{{board.Position}}</div>                                
                        <h3 ><a href="{% url 'innova:ourboardhash' hash=board.id %}">{{board.name}}</a></h3>
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</section>
{% endblock %}

templates/webPage/apply-filter.html
{% for product in products %}
<div class="flat-blog-grid">                               
    <div class="grid-post style-post">
        <div class="img-box">
            <div class="media">
                <img src="{{product.Image.url}}" alt="images">
            </div>
        </div>                                      
        <div class="content">
            <h3 class="title-item">{{product.name}}</h3>
            <p>{{product.description|slice:":100"}}....
                <h5>To access the appropriate content please confirm if you are </h5>
            </p>
            
            <div class="read-more link-style-3">
                
                <div class="row">
                    <div class="col-lg-5">
                        <a href="{% url 'innova:productDetails' productcategory=product.product_category product=product.name %}">a member of the public</a>
                    </div>
                    <div class="col-lg-2">
                        <p> or </p>
                    </div>
                    <div class="col-lg-5">
                        <a href="{% url 'innova:patientsArea' product=product.name %}">a healthcare professional</a>
                    </div>
                </div>
            </div>
        </div>
    </div>                                                      
</div> 
{% endfor %}                 
<div class="themesflat-pagination clearfix">
    {% if products.has_other_pages %}

        <ul>
            {% if products.has_previous %}
            <li>
                <a class="page-numbers prev-style" onclick="applyPaginator({{ products.previous_page_number }})" tabindex="-1">Prev</a>
            </li>
            {% endif %}
            <li>
                <a class="page-numbers" onclick="applyPaginator({{ products.number }})">{{ products.number }}</a>
            </li>
            {% if products.has_next %}
            <li>
                <a class="page-numbers next-style" onclick="applyPaginator({{ products.next_page_number }})">Next</a>
            </li>
            {% endif %}
        </ul>

    {% endif %}
</div>     

templates/webPage/food-supplements.html
{% extends 'mainTemplates/mainPage.html' %}
{% load static %}
{% load humanize %}

{% block section1 %}
<section class="flat-title-page">
    <div class="overlay-slider style"></div>
    <div class="overlay-page">
        <img src="{% static 'assets/images/mark-page/Therapeutic-areas2.png' %}" alt="img">
    </div>
    <div class="container">
        <div class="row">                          
            <div class="zup col-lg-12 col-md-12">                              
                <div class="breadcrumbs">
                    <h1>Therapeutic areas<span class="style-color">.</span></h1>
                    <div class="breadcrumb-trail link-style-2">
                        <a class="home" href="{% url 'innova:Home' %}">Home Page</a><span>Food Supplements</span>
                    </div>
                </div>                                                           
            </div>                          
        </div>
    </div>
</section>
{% endblock %}

{% block section2 %}
<div class="tf-space flat-blog flat-blog-details">
    <div class="container">
        <div class="row"> 
            <div id="loadData" class="col-lg-8 col-md-12">                  
                {% for product in products %}
                <div class="flat-blog-grid wow fadeInDown" data-wow-delay="100ms" data-wow-duration="800ms">                               
                    <div class="grid-post style-post">
                        <div class="img-box">
                            <div class="media">
                                <img src="{{product.Image.url}}" alt="images">
                            </div>
                        </div>                                      
                        <div class="content">
                            <h3 class="title-item">{{product.name}}</h3>
                            <p>{{product.description|slice:":100"}}....
                                <h5>To access the appropriate content please confirm if you are </h5>
                            </p>
                            
                            <div class="read-more link-style-3">
                                
                                <div class="row">
                                    <div class="col-lg-5">
                                        <a href="{% url 'innova:productDetailsFood' productcategory=product.product_category product=product.name %}">a healthcare professional</a>
                                    </div>
                                    <div class="col-lg-2">
                                        <p> or </p>
                                    </div>
                                    <div class="col-lg-5">
                                        <a href="{% url 'innova:patientsAreaFood' product=product.name %}">a member of the public</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>                                                      
                </div> 
                {% endfor %}                 
                <div class="themesflat-pagination clearfix">
                    {% if products.has_other_pages %}

                        <ul>
                            {% if products.has_previous %}
                            <li>
                                <a class="page-numbers prev-style" onclick="applyPaginator({{ products.previous_page_number }})" tabindex="-1">Prev</a>
                            </li>
                            {% endif %}
                            <li>
                                <a class="page-numbers" onclick="applyPaginator({{ products.number }})">{{ products.number }}</a>
                            </li>
                            {% if products.has_next %}
                            <li>
                                <a class="page-numbers next-style" onclick="applyPaginator({{ products.next_page_number }})">Next</a>
                            </li>
                            {% endif %}
                        </ul>

                    {% endif %}
                </div>                                                                                                                          
            </div>                      
            <div class="col-lg-4 col-md-12 wow fadeInLeft" data-wow-delay="100ms" data-wow-duration="800ms">
                <aside class="side-bar">
                    <div class="inner-side-bar">                                       
                        <div class="widget search">
                            <div class="widget-title">
                                <h3>Search Here</h3>                                       
                            </div>
                            <form role="search" id="ApplyFilter" class="search-form">
                                {% csrf_token %}
                                            <input type="hidden" name="page" id="pagenumber" value="{{ products.number }}">
                                            <input type="hidden" name="product_category" id="productCategory">
                                            <!--<input type="{{myFilter.form.product_category.widget_type}}" class="search-field" maxlength="{{myFilter.form.product_category.field.max_length}}" name="{{ myFilter.form.product_category.html_name }}" placeholder="Enter {{ myFilter.form.product_category.label }}"  {% if myFilter.form.product_category.value is not None %} value="{{ myFilter.form.product_category.value }}" {% endif %}> -->
                                            <input type="{{myFilter.form.name.widget_type}}" class="search-field" maxlength="{{myFilter.form.name.field.max_length}}" name="{{ myFilter.form.name.html_name }}" placeholder="Search Product"  {% if myFilter.form.product_category.value is not None %} value="{{ myFilter.form.name.value }}" {% endif %}>
                                            <button class="search-icon search-submit" type="submit" title="Search" ></button>
                            </form>
                        </div>
                        <div class="widget widget-categories"> 
                            <div class="widget-title item">
                                <h3>Category</h3>  
                            </div>                                                                                                                     
                            <ul>
                                <li>
                                    <a onclick="applyCategory('')">All</a>
                                </li>
                                {% for Category  in productCategory %}
                                <li>
                                    <a onclick="applyCategory({{Category.id}})">{{Category}}</a>
                                </li>
                                {% endfor %} 
                            </ul>
                        </div>                             
                    </div>
                </aside>
            </div>                     
        </div>                      
    </div>
</div>
{% endblock %}

{% block js2 %}
<script>
    $('#ApplyFilter').on('submit',function(e){

        e.preventDefault();
        var formData = new FormData(this);
        console.log(formData)

        $.ajax({
                url: "{% url 'innova:applyFilter' category=2 %}",
                type:'POST',
                data:formData,
                success: function(data) {
                    console.log('success');
                    $("#loadData").html(data);
                },
                error: function (data) {
                    console.log('error');
                    message = '<div class="alert alert-danger mb-0" role="alert"> \
                                        <strong>Oh snap!</strong> \
                                        Change a few things up and try submitting again, or contact with Admin \
                                    </div>';
                        
                        $("#loadData").html(message)
                },
                cache: false,
                contentType: false,
                processData: false
        });

    });

function applyPaginator(pageNum) {
    $('#pagenumber').val(pageNum);
    $('#ApplyFilter').submit();
}

function applyCategory(category){
    $('#productCategory').val(category);
    $('#ApplyFilter').submit();
}

</script>
{% endblock %}

templates/webPage/plasma-protein.html
{% extends 'mainTemplates/mainPage.html' %}
{% load static %}
{% load humanize %}

{% block section1 %}
<section class="flat-title-page">
    <div class="overlay-slider style"></div>
    <div class="overlay-page">
        <img src="{% static 'assets/images/mark-page/Therapeutic-areas1.png' %}" alt="img">
    </div>
    <div class="container">
        <div class="row">                          
            <div class="zup col-lg-12 col-md-12">                              
                <div class="breadcrumbs">
                    <h1>Therapeutic areas<span class="style-color">.</span></h1>
                    <div class="breadcrumb-trail link-style-2">
                        <a class="home" href="{% url 'innova:Home' %}">Home Page</a><span>Plasma Protein</span>
                    </div>
                </div>                                                           
            </div>                          
        </div>
    </div>
</section>
{% endblock %}

{% block section2 %}
<div class="tf-space flat-blog flat-blog-details">
    <div class="container">
        <div class="row"> 
            <div id="loadData" class="col-lg-8 col-md-12">                  
                {% for product in products %}
                <div class="flat-blog-grid wow fadeInDown" data-wow-delay="100ms" data-wow-duration="800ms">                               
                    <div class="grid-post style-post">
                        <div class="img-box">
                            <div class="media">
                                <img src="{{product.Image.url}}" alt="images">
                            </div>
                        </div>                                      
                        <div class="content">
                            <h3 class="title-item">{{product.name}}</h3>
                            <p>{{product.description|slice:":100"}}....
                                <h5>To access the appropriate content please confirm if you are </h5>
                            </p>
                            
                            <div class="read-more link-style-3">
                                
                                <div class="row">
                                    <div class="col-lg-5">
                                        <a href="{% url 'innova:productDetails' productcategory=product.product_category product=product.name %}">a healthcare professional</a>
                                    </div>
                                    <div class="col-lg-2">
                                        <p> or </p>
                                    </div>
                                    <div class="col-lg-5">
                                        <a href="{% url 'innova:patientsArea' product=product.name %}">a member of the public</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>                                                      
                </div> 
                {% endfor %}                 
                <div class="themesflat-pagination clearfix">
                    {% if products.has_other_pages %}

                        <ul>
                            {% if products.has_previous %}
                            <li>
                                <a class="page-numbers prev-style" onclick="applyPaginator({{ products.previous_page_number }})" tabindex="-1">Prev</a>
                            </li>
                            {% endif %}
                            <li>
                                <a class="page-numbers" onclick="applyPaginator({{ products.number }})">{{ products.number }}</a>
                            </li>
                            {% if products.has_next %}
                            <li>
                                <a class="page-numbers next-style" onclick="applyPaginator({{ products.next_page_number }})">Next</a>
                            </li>
                            {% endif %}
                        </ul>

                    {% endif %}
                </div>                                                                                                                          
            </div>                      
            <div class="col-lg-4 col-md-12 wow fadeInLeft" data-wow-delay="100ms" data-wow-duration="800ms">
                <aside class="side-bar">
                    <div class="inner-side-bar">                                       
                        <div class="widget search">
                            <div class="widget-title">
                                <h3>Search Here</h3>                                       
                            </div>
                            <form role="search" id="ApplyFilter" class="search-form">
                                {% csrf_token %}
                                            <input type="hidden" name="page" id="pagenumber" value="{{ products.number }}">
                                            <input type="hidden" name="product_category" id="productCategory">
                                            <!--<input type="{{myFilter.form.product_category.widget_type}}" class="search-field" maxlength="{{myFilter.form.product_category.field.max_length}}" name="{{ myFilter.form.product_category.html_name }}" placeholder="Enter {{ myFilter.form.product_category.label }}"  {% if myFilter.form.product_category.value is not None %} value="{{ myFilter.form.product_category.value }}" {% endif %}> -->
                                            <input type="{{myFilter.form.name.widget_type}}" class="search-field" maxlength="{{myFilter.form.name.field.max_length}}" name="{{ myFilter.form.name.html_name }}" placeholder="Search Product"  {% if myFilter.form.product_category.value is not None %} value="{{ myFilter.form.name.value }}" {% endif %}>
                                            <button class="search-icon search-submit" type="submit" title="Search" ></button>
                            </form>
                        </div>
                        <div class="widget widget-categories"> 
                            <div class="widget-title item">
                                <h3>Category</h3>  
                            </div>                                                                                                                     
                            <ul>
                                <li>
                                    <a onclick="applyCategory('')">All</a>
                                </li>
                                {% for Category  in productCategory %}
                                <li>
                                    <a onclick="applyCategory({{Category.id}})">{{Category}}</a>
                                </li>
                                {% endfor %} 
                            </ul>
                        </div>                             
                    </div>
                </aside>
            </div>                     
        </div>                      
    </div>
</div>
{% endblock %}

{% block js2 %}
<script>
    $('#ApplyFilter').on('submit',function(e){

        e.preventDefault();
        var formData = new FormData(this);
        console.log(formData)

        $.ajax({
                url: "{% url 'innova:applyFilter' category=1 %}",
                type:'POST',
                data:formData,
                success: function(data) {
                    console.log('success');
                    $("#loadData").html(data);
                },
                error: function (data) {
                    console.log('error');
                    message = '<div class="alert alert-danger mb-0" role="alert"> \
                                        <strong>Oh snap!</strong> \
                                        Change a few things up and try submitting again, or contact with Admin \
                                    </div>';
                        
                        $("#loadData").html(message)
                },
                cache: false,
                contentType: false,
                processData: false
        });

    });

function applyPaginator(pageNum) {
    $('#pagenumber').val(pageNum);
    $('#ApplyFilter').submit();
}

function applyCategory(category){
    $('#productCategory').val(category);
    $('#ApplyFilter').submit();
}

</script>
{% endblock %}