account/urls.py
from django.urls import path
from . import views

app_name = 'account'


urlpatterns = [
    path('',views.redirectHome,name='redirectHome'),
    path('<str:app>/<str:slug>',views.navpage,name='navpage'),
]

innova/urls.py
from django.urls import path
from . import views

app_name = 'innova'


urlpatterns = [

    path('',views.home,name='Home'),
    path('company',views.company,name='company'),
    path('our-board',views.ourBoard,name='our-board'),
    path('reporting',views.reporting,name='reporting'),
    path('plasma-protein',views.plasmaProtein,name='plasma-protein'),
    path('food-supplements',views.foodSupplements,name='food-supplements'),
    path('careers',views.careers,name='careers'),
    path('contact',views.contact,name='contact'),
    path('applyFilter/<int:category>',views.applyFilter,name='applyFilter'),

    path('ProductDetails/<str:productcategory>/<str:product>',views.productDetails,name='productDetails'),
    path('ProductDetails/<str:product>',views.patientsArea,name='patientsArea'),

    path('productDetailsFood/<str:productcategory>/<str:product>',views.productDetailsFood,name='productDetailsFood'),
    path('productDetailsFood/<str:product>',views.patientsAreaFood,name='patientsAreaFood'),

    path('News/<int:id>',views.newsDetails,name='newsDetails'),
    path('Ourboard/<int:hash>',views.ourBoardHash,name='ourboardhash'),
    path('Company/<int:hash>',views.companyhash,name='companyhash'),

]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('innova/',include('innova.urls',namespace='innova')),
    path('',include('account.urls',namespace='account')),
    path("__debug__/", include("debug_toolbar.urls"))
]

urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/mainTemplates/footer.html
<footer id="footer" class="clearfix">
    <div id="footer-widgets" class="container">
        <div class="row">
            <div class="col-lg-6 col-md-6">
                <div class="widget">
                    <h4 class="text-color-1">Innova</h4>
                    <h5 class="text-color-4">We empower the fight for health and well being as a human right.</h5>
                </div>
                <ul class="widget-list-media">
                    <li>        
                        <a href="#"><i class="fab fa-facebook-f"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fab fa-twitter"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fab fa-linkedin-in"></i></a>
                    </li>
                </ul>                          
            </div>
            <div class="col-lg-6 col-md-6">
                <div class="menu-2">
                    <h3 class="widget-title-link-wrap text-color-1">Office</h3>
                    <ul class="widget-list-contact">
                        <li class="meta-address text-color-4">
                            <i class="fa fa-map-marker" aria-hidden="true"> 17, Taka st. 11391, Nasr City, Cairo, Egypt.</i>
                        </li>
                        <li class="meta-address text-color-4">
                            <i class="fa fa-envelope" aria-hidden="true"> innova@innovahealthcare.net</i>
                        </li>
                        <li class="meta-address text-color-4">
                            <i class="fa fa-phone" aria-hidden="true"> + 202 2472 8167</i></a>
                        </li>
                        <li class="meta-address text-color-4">
                            <i class="fa fa-fax" aria-hidden="true"> + 202 2472 8169</i>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>             
</footer><!-- /#footer -->
<div class="widget-social-footer">
    <div class="container">
        <h3>Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | 
            <!-- <a href="https://www.istrotech.com/" target="_blank">  -->
                Egygate Marketing Agency
            <!-- </a> -->
        </h3>                            
    </div>
</div>

templates/mainTemplates/header.html
{% load static %}
<head>
    <!-- Basic Page Needs -->
    <meta charset="utf-8">
    <title>Innova</title>

    <meta name="author" content="innova@innovahealthcare.net">

    <!-- Mobile Specific Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Theme Style -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css'%}">

    <!-- Reponsive -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/responsive.css'%}">

    <!-- Swiper slide -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/swiper-bundle.min.css'%}">

    <!-- Favicon and Touch Icons  -->
    <link rel="shortcut icon" href="{% static 'assets/icon/Favicon.png'%}">
    <link rel="apple-touch-icon-precomposed" href="{% static 'assets/icon/Favicon.png'%}">

    {% block css %}
    
    {% endblock %}

</head>

templates/mainTemplates/mainPage.html
{% load static %}
<!DOCTYPE html>
<html>

    {% include 'mainTemplates/header.html' %}

    <body class="header-fixed counter-scroll">

        <!-- preloader -->
        <div class="preload preload-container">
           <!-- <div class="preload-logo"></div> -->
           <div class="preload-page animate-rotate">
                <img src="{% static 'assets/images/mark-page/Innova.png' %}" class="img-max_width" alt="img">
            </div>

        </div>
        <!-- /preloader -->

        <!-- wrapper -->
        <div id="wrapper" class="animsition">

            <!-- page -->
            <div id="page" class="clearfix">

                {% include 'mainTemplates/navbar.html' %}



                {% block section1 %}
    
                {% endblock %}

                {% block section2 %}
    
                {% endblock %}

                {% block section3 %}
    
                {% endblock %}

                {% block section4 %}
    
                {% endblock %}

                {% block section5 %}
    
                {% endblock %}

                {% block section6 %}
    
                {% endblock %}

                {% block section7 %}
    
                {% endblock %}

                {% include 'mainTemplates/footer.html' %}



            </div>
            <!-- /#page -->

        </div>
        <!-- /wrapper -->

        <a id="scroll-top"></a>

        {% include 'mainTemplates/script.html' %}

        {% block js2 %}
    
        {% endblock %}
    </body>

</html>

templates/mainTemplates/navbar.html
{% load static %}
<div id="site-header-wrap">    
    <header id="site-header" class="header-style3">
        <div class="container">
            <div class="row">                          
                <div class=" col-lg-2 col-sm-9">
                    <div id="site-logo" class="clearfix logo-home2">
                        <div id="site-log-inner">
                            <a href="{% url 'innova:Home' %}" rel="home" class="main-logo">
                                <img src="{% static 'assets/images/logo/Logo.png' %}" alt="Innova" width="150" height="26" data-retina="assets/images/logo/logo-header@2x.png" data-width="96" data-height="26">
                            </a>
                        </div>
                    </div>
                </div>
                
                <!-- /.mobile-button -->
                <!-- /#site-logo -->
                <div class=" col-lg-10 col-sm-3">
                    <div class="mobile-button home2 home3">
                        <span></span>
                    </div>
                    <div id="site-header-inner" class="style-2">
                        <div class="wrap-inner clearfix">
                            <nav id="main-nav" class="main-nav ">
                                <ul id="menu-primary-menu" class="menu">
                                    {% for Mlist in bardata %}
                                        {% if Mlist.child_list_flag == False %}
                                            <li class="menu-item">
                                                <a href="{% url 'account:navpage' app=Mlist.folder_url slug=Mlist.file_name %}">{{Mlist.title}}</a>
                                            </li>
                                        {% else %}    
                                            {% if 'Company' in Mlist.title %}
                                            <li class="menu-item">
                                                <a>{{Mlist.title}}</a>
                                                <ul class="sub-menu" style="display: block;">
                                                    {% for info in companyInformation %}
                                                    <li class="menu-item"><a href="{% url 'innova:companyhash' hash=info.id %}">{{info.name}}</a></li>
                                                    {% endfor %}
                                                    <li class="menu-item"><a href="/innova/our-board">Leadership Team</a></li>	
                                                </ul>
                                            </li>
                                            {% else %}
                                            <li class="menu-item">
                                                <a>{{Mlist.title}}</a>
                                                <ul class="sub-menu">
                                                    {% for chlist in childbardata %}
                                                        {% if chlist.parent_id == Mlist.id %}
                                                            <li class="menu-item"><a href="{% url 'account:navpage' app=chlist.folder_url slug=chlist.file_name %}">{{chlist.title}}</a></li>  
                                                        {% endif %}      
                                                    {% endfor %}											
                                                </ul>
                                            </li>
                                            {% endif %}
                                        {% endif %}
                                    {% endfor %}
                                </ul>
                            </nav>
                            <!-- /#main-nav -->
                        </div>
                        <!-- /.wrap-inner -->
                    </div>
                    <div class="tf-button home2"><a href="{% url 'innova:contact' %}" class="button style btn-1">Contact Us</a></div> 
                </div>                         
            </div>
        </div>
        <!-- /#site-header-inner -->               
    </header>
    <!-- /#site-header -->
</div>
<!-- #site-header-wrap -->

templates/mainTemplates/script.html
{% load static %}
<!-- Javascript -->
<script src="{% static 'assets/js/jquery.min.js' %}"></script>
<script src="{% static 'assets/js/countto.js' %}"></script>
<script src="{% static 'assets/js/wow.min.js' %}"></script>
<script src="{% static 'assets/js/main.js' %}"></script>
<script src="{% static 'assets/js/shortcodes.js' %}"></script>
<script src="{% static 'assets/js/jquery.easing.js' %}"></script>
<script src="{% static 'assets/js/jquery.fancybox.js' %}"></script>
<script src="{% static 'assets/js/plugin.js' %}"></script>

{% block js %}
    
{% endblock %}

<!-- Swiper slide -->
<script src="{% static 'assets/js/swiper-bundle.min.js' %}"></script>
<script src="{% static 'assets/js/swiper.js' %}"></script>